window.variants = window.variants || {};
window.variants.dog = { // Is used for constants.PET_BREEDS
	beagle: ['Tricolour', 'Lemon & White'],
	golden_retriever: ['Golden'],
	yorkshire_terrier: ['Black & Tan'],
	miniature_dachshund: ['Red', 'Black & Tan'],
	chihuahua1: ['Cream'],
	chihuahua2: ['Red & White', 'Tricolour'],
	toy_poodle1: ['Fluffy Muzzle'],
	toy_poodle2: ['Clipped Muzzle'],
	shiba: ['Red & White', 'Black & Tan'],
	labrador_retriever: ['Yellow', 'Black', 'Chocolate'],
	spaniel: ['Blentheim', 'Tricolour', 'Ruby'],
	pug: ['Silver', 'Black', 'Apricot'],
	shih_tzu: ['Brown & White', 'Brindle & White'],
	shetland_sheepdog: ['Sable & White', 'Bicolour', 'Tricolour'],
	miniature_schnauzer: ['Pepper & Salt'],
	pembroke_welsh_corgi: ['Sable & White', 'Tricolour'],
	miniature_pinscher: ['Black & Tan', 'Red'],
	german_shepherd_dog: ['Black & Tan', 'Sable'],
	jack_russell_terrier: ['Lemon & White', 'Black & White'],
	siberian_husky: ['Black & White', 'Brown & White', 'Agouti & White'],
	boxer: ['Fawn & White', 'Brindle & White'],
	dalmatian: ['With Spots'],
	pomeranian: ['Orange', 'Black & Tan', 'Parti-Coloured'],
	french_bulldog: ['Black & White', 'Brindle', 'Fawn'],
	cocker_spaniel: ['Parti-Coloured', 'Red'],
	maltese: ['', '', '', '', '', '', '', '', '', '', '', '', 'White'],
	great_dane: ['Mantle', 'Harlequin', 'Fawn'],
	bull_terrier: ['Black & White', 'Brindle & White', 'Red & White'],
	basset_hound: ['Tricolour', 'Lemon & White'],
	robo_pup: ['Untitled']
}