window.SavegameEditor.Constants.CHARACTERS=[
	'Abraham Lincoln',
	'Bad Cop',
	'Bandit',
	'Batman',

	'Benny',
	'Blaze Firefighter',
	'Bruce Wayne',
	'Calamity Drone',

	'Cardio Carrie',
	'Cavalry',
	'Caveman',
	'Cleopatra',

	'Deputron',
	'Dr McScrubs',
	'El Macho Wrestler',
	'Emmet (Piece of Resistance)',

	'Emmet (Clown)',
	'Emmet (Construction)',
	'Emmet (Lizard)',
	'Emmet (Magician)',

	'Emmet (Master Builder)',
	'Emmet (PJs)',
	'Emmet (Robin Hood)',
	'Emmet (Robot)',

	'Emmet (Shower)',
	'Emmet (Surgeon)',
	'Emmet (Old West)',
	'Foreman Frank',

	'Gail',
	'Gallant Guard',
	'Gandalf',
	'Garbage Man Dan',

	'Good Cop',
	'Good Cop (Scribble Face)',
	'Gordon Zola',
	'Green Lantern',

	'Green Ninja',
	'Hank Haystack',
	'Ice Cream Jo',
	'Johnny Thunder',

	'Kabob Bob',
	'Lady Liberty',
	'Larry the Barrista',
	'Swamp Creature',

	'Lord Business',
	'Lord Vampyre',
	'Ma Cop',
	'Michelangelo',

	'Mrs Scratchen-Post',
	'Mummy',
	'Native Chief',
	'Natitve Warrior',

	'Outlaw',
	'Pa Cop',
	'Panda Guy',
	'Plumber Joe',

	'President Business',
	'Prospector',
	'Robo Construction',
	'Robo Cowboy',

	'Robo Demolition',
	'Robo Agent',
	'Robo Pilot',
	'Robo Receptionist',

	'Rootbeer Belle',
	'S.S.P Officer',
	'S.S.P Officer (Beanie)',
	'S.S.P Officer (Heavy)',

	'S.S.P Officer (SWAT)',
	'Sharon Shoehorn',
	'Sheriff Not-A-Robot',
	'Sir Stackabrick',

	'Sudds Backwash',
	'Superman',
	'Taco Tuesday Guy',
	'Test Dummy',

	'Unikitty',
	'Unikitty (Business)',
	'Unikitty (Queasy)',
	'Unikitty (Space)',

	'Velma Staplebot',
	'Vitruvius',
	'Vitruvius (Young)',
	'"Where Are My Pants?" Guy',

	'Wiley Fusebot',
	'William Shakespeare',
	'Wonder Woman',
	'Wyldstyle',

	'Wyldstyle (Hooded)',
	'Wyldstyle (Robot)',
	'Wyldstyle (Space)',
	'Wyldstyle (Old West)'
];
window.SavegameEditor.Constants.LEVELS=[
	{value:0, name:'Prologue - The Prophecy'},
	{value:1, name:'Prologue - Building Site'},
	{value:2, name:'Prologue - The Piece'},
	{value:3, name:'Police Station - Melting Chamber'},
	{value:4, name:'Police Station - Alley Escape'},
	{value:5, name:'Police Station - Bike Chase'},
	{value:6, name:'Flatbush Gulch - The Portal'},
	{value:7, name:'Flatbush Gulch - Hillside Slide'},
	{value:8, name:'Flatbush Gulch - Desert Path'},
	{value:9, name:'Flatbush Town - Town Outskirts'},
	{value:10, name:'Flatbush Town - Town Entrance'},
	{value:11, name:'Flatbush Town - Saloon Showdown'},
	{value:12, name:'Flatbush Rooftops - Rooftop Ambush'},
	{value:13, name:'Flatbush Rooftops - Rooftop Escape'},
	{value:14, name:'Flatbush Rooftops - Rooftop Brawl'},
	{value:15, name:'Flatbush Chase - Flatbush Canyon'},
	{value:16, name:'Flatbush Chase - Train Escape'},
	{value:17, name:'Flatbush Chase - Train Engine'},
	{value:18, name:'Cloud Cuckoo Land - Middle Zealand'},
	{value:19, name:'Cloud Cuckoo Land - Cloud Entrance'},
	{value:20, name:'Cloud Cuckoo Land - Dance Street'},
	{value:21, name:'Cloud Under Attack - Cloud Escape'},
	{value:22, name:'Cloud Under Attack - Cuckoo Castle'},
	{value:23, name:'Cloud Under Attack - Dropship Chase'},
	{value:24, name:'Submarine - Submarine Attack'},
	{value:25, name:'Submarine - Submarine Interior'},
	{value:26, name:'Submarine - MetalBeard\'s Ship'},
	{value:27, name:'Business HQ - Octan Airlock'},
	{value:28, name:'Business HQ - Octan Hangar'},
	{value:29, name:'Business HQ - The Relic Room'},
	{value:30, name:'The Kragle - Assembly Room'},
	{value:31, name:'The Kragle - Kragle Shutdown'},
	{value:32, name:'The Kragle - Think Tank'},
	{value:33, name:'TV Station - Office Corridors'},
	{value:34, name:'TV Station - Server Room'},
	{value:35, name:'TV Station - TV Broadcast'},
	{value:36, name:'Spaceship Escape - TV Prop Room'},
	{value:37, name:'Spaceship Escape - Middle Zealand Canyons'},
	{value:38, name:'Spaceship Escape - Bricksburg Skies'},
	{value:39, name:'Attack on Bricksburg - Return to Bricksburg'},
	{value:40, name:'Attack on Bricksburg - Bricksburg Streets'},
	{value:41, name:'Attack on Bricksburg - Bricksburg Assault'},
	{value:42, name:'The Cube Ship - Battle for Bricksburg'},
	{value:43, name:'The Cube Ship - Cube Ship Approach'},
	{value:44, name:'The Cube Ship - Business Time'}
];
window.SavegameEditor.Constants.UPGRADES=[
	'Always Charged',
	'Fast Use',
	'Collectable Detector',
	'Fast Builder',
	'Mini Game Master',
	'Invicibility',
	'Health Regeneration',
	'Stud Magnet',
	'Confetti Effects',
	'Bubble Effects',
	'Extra Heart',
	'X8 Stud Multiplier',
	'X6 Stud Multiplier',
	'X4 Stud Multiplier',
	'X2 Stud Multiplier'
];