services:
  webserver:
    build:
      context: ..
      dockerfile: server/Dockerfile
    volumes:
      - ${SAVE_PATH}:/app/data
    ports:
      - "3000:3000"
    container_name: botw-webserver
    restart: unless-stopped